export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

export const REQUEST_ROBORS_PENDING = 'REQUEST_ROBORS_PENDING';
export const REQUEST_ROBORS_SUCCESS = 'REQUEST_ROBORS_SUCCESS';
export const REQUEST_ROBORS_FAILED = 'REQUEST_ROBORS_FAILED';